# ----------- DistilBERT - finetuned_ai4privacy_v2 -----------

DistilBERT is a streamlined version of the BERT model, designed for faster training and inferencing on off-cloud servers, making it a suitable choice for applications with constraints on computational resources (Wei et al., 2022). As a distilled version of BERT, DistilBERT maintains a significant proportion of the original model's capabilities, including 97% of BERT's language understanding proficiency, while offering the advantages of being 60% faster and 40% smaller (Sanh et al., 2019).

The model has demonstrated its efficacy across various applications, such as suicidal intention detection in social media posts (Ananthakrishnan et al., 2022) and opinion holder detection (Al-Mahmud & Shimada, 2022). This versatility is attributable to its robust foundational architecture derived from BERT, coupled with enhancements in efficiency and speed.

1. Wei, F., Yang, J., Mao, Q., Qin, H., & Dabrowski, A. (2022). An Empirical Comparison of DistilBERT, Longformer and Logistic Regression for Predictive Coding. 2022 IEEE International Conference on Big Data (Big Data). 

    - URL: https://ieeexplore.ieee.org/document/10020486
    
2. Sanh, V., Debut, L., Chaumond, J., & Wolf, T. (2019). DistilBERT, a distilled version of BERT: smaller, faster, cheaper and lighter. ArXiv. 

    - URL: https://www.semanticscholar.org/paper/DistilBERT%2C-a-distilled-version-of-BERT%3A-smaller%2C-Sanh-Debut/a54b56af24bb4873ed0163b77df63b92bd018ddc

3. Ananthakrishnan, G., Jayaraman, A. K., Trueman, T., Mitra, S., A K, A., & Murugappan, A. (2022). Suicidal Intention Detection in Tweets Using BERT-Based Transformers. 2022 International Conference on Computing, Communication, and Intelligent Systems (ICCCIS). 

    - URL: https://ieeexplore.ieee.org/document/10037677

4. Al-Mahmud, & Shimada, K. (2022). Dataset Construction and Classification Based on Pre-trained Models for Opinion Holder Detection. 2022 12th International Congress on Advanced Applied Informatics (IIAI-AAI). 

    - URL: https://ieeexplore.ieee.org/document/9894524

### DistilBERT:
Paper: https://arxiv.org/abs/1910.01108

Huggingface: https://huggingface.co/distilbert-base-uncased

Documentation: https://huggingface.co/docs/transformers/main/en/model_doc/distilbert

### ai4privacy:
Huggingface: https://huggingface.co/ai4privacy

Model: https://huggingface.co/Isotonic/distilbert_finetuned_ai4privacy_v2

GitHub: https://github.com/Sripaad/ai4privacy

## Libraries

In [1]:
from transformers import pipeline, AutoTokenizer, AutoModelForTokenClassification
import pandas as pd
from sklearn.metrics import precision_score, recall_score, f1_score
from IPython.display import display, HTML
from collections import Counter
import numpy as np

display(HTML("<style>.container { width:100% !important; }</style>"))

In [2]:
# Load the model
model_name = "Isotonic/distilbert_finetuned_ai4privacy_v2"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForTokenClassification.from_pretrained(model_name)

In [3]:
nlp = pipeline("token-classification", model=model, tokenizer=tokenizer)

text = "My name is Max and im from Frankfurt. I study at the University of Mannheim."
results = nlp(text)

results

[{'entity': 'B-FIRSTNAME',
  'score': 0.86211693,
  'index': 4,
  'word': 'max',
  'start': 11,
  'end': 14},
 {'entity': 'B-STATE',
  'score': 0.9750011,
  'index': 8,
  'word': 'frankfurt',
  'start': 27,
  'end': 36},
 {'entity': 'B-STATE',
  'score': 0.9271666,
  'index': 16,
  'word': 'mannheim',
  'start': 67,
  'end': 75}]

In [4]:
labels = model.config.id2label
print(labels)

{0: 'O', 1: 'B-PHONEIMEI', 2: 'I-PHONEIMEI', 3: 'B-JOBAREA', 4: 'B-FIRSTNAME', 5: 'I-FIRSTNAME', 6: 'B-VEHICLEVIN', 7: 'I-VEHICLEVIN', 8: 'B-AGE', 9: 'B-GENDER', 10: 'I-GENDER', 11: 'B-HEIGHT', 12: 'I-HEIGHT', 13: 'B-BUILDINGNUMBER', 14: 'I-BUILDINGNUMBER', 15: 'B-MASKEDNUMBER', 16: 'I-MASKEDNUMBER', 17: 'B-PASSWORD', 18: 'I-PASSWORD', 19: 'B-DOB', 20: 'I-DOB', 21: 'B-IPV6', 22: 'I-IPV6', 23: 'B-NEARBYGPSCOORDINATE', 24: 'I-NEARBYGPSCOORDINATE', 25: 'B-USERAGENT', 26: 'I-USERAGENT', 27: 'B-TIME', 28: 'I-TIME', 29: 'B-JOBTITLE', 30: 'I-JOBTITLE', 31: 'B-COUNTY', 32: 'B-EMAIL', 33: 'I-EMAIL', 34: 'B-ACCOUNTNUMBER', 35: 'I-ACCOUNTNUMBER', 36: 'B-PIN', 37: 'I-PIN', 38: 'B-EYECOLOR', 39: 'I-EYECOLOR', 40: 'B-LASTNAME', 41: 'I-LASTNAME', 42: 'I-JOBAREA', 43: 'B-IPV4', 44: 'I-IPV4', 45: 'B-DATE', 46: 'I-DATE', 47: 'B-STREET', 48: 'I-STREET', 49: 'B-CITY', 50: 'I-CITY', 51: 'B-PREFIX', 52: 'I-PREFIX', 53: 'B-CREDITCARDISSUER', 54: 'B-CREDITCARDNUMBER', 55: 'I-CREDITCARDNUMBER', 56: 'I-CREDITCARDISSUER', 57: 'B-MIDDLENAME', 58: 'B-STATE', 59: 'I-STATE', 60: 'B-VEHICLEVRM', 61: 'I-VEHICLEVRM', 62: 'B-ORDINALDIRECTION', 63: 'B-SEX', 64: 'B-JOBTYPE', 65: 'I-JOBTYPE', 66: 'B-CURRENCYCODE', 67: 'I-CURRENCYCODE', 68: 'B-CURRENCYSYMBOL', 69: 'I-AMOUNT', 70: 'B-ACCOUNTNAME', 71: 'I-ACCOUNTNAME', 72: 'B-BITCOINADDRESS', 73: 'I-BITCOINADDRESS', 74: 'B-LITECOINADDRESS', 75: 'I-LITECOINADDRESS', 76: 'B-PHONENUMBER', 77: 'I-PHONENUMBER', 78: 'B-MAC', 79: 'I-MAC', 80: 'B-CURRENCY', 81: 'B-IBAN', 82: 'I-IBAN', 83: 'B-COMPANYNAME', 84: 'I-COMPANYNAME', 85: 'B-CURRENCYNAME', 86: 'I-CURRENCYNAME', 87: 'I-CURRENCYSYMBOL', 88: 'B-ZIPCODE', 89: 'I-ZIPCODE', 90: 'B-SSN', 91: 'I-SSN', 92: 'B-AMOUNT', 93: 'I-CURRENCY', 94: 'B-URL', 95: 'I-URL', 96: 'B-IP', 97: 'I-IP', 98: 'B-SECONDARYADDRESS', 99: 'I-SECONDARYADDRESS', 100: 'B-USERNAME', 101: 'I-USERNAME', 102: 'B-ETHEREUMADDRESS', 103: 'I-ETHEREUMADDRESS', 104: 'B-CREDITCARDCVV', 105: 'I-CREDITCARDCVV', 106: 'I-COUNTY', 107: 'I-AGE', 108: 'I-MIDDLENAME', 109: 'B-BIC', 110: 'I-BIC'}

In [5]:
data = pd.read_json("../../data/dataset_english.json")
data

,masked_text,unmasked_text,privacy_mask,span_labels,bio_labels,tokenised_text
0,A students assessment was found on device bear...,A students assessment was found on device bear...,"{'[PHONEIMEI_1]': '06-184755-866851-3', '[JOBA...","[[0, 57, O], [57, 75, PHONEIMEI_1], [75, 138, ...","[O, O, O, O, O, O, O, O, O, O, O, O, O, B-PHON...","[a, student, s, assessment, was, found, on, de..."
1,"Dear [FIRSTNAME_1], as per our records, your l...","Dear Omer, as per our records, your license 78...","{'[FIRSTNAME_1]': 'Omer', '[VEHICLEVIN_1]': '7...","[[0, 5, O], [5, 9, FIRSTNAME_1], [9, 44, O], [...","[O, B-FIRSTNAME, I-FIRSTNAME, O, O, O, O, O, O...","[dear, om, ##er, ,, as, per, our, records, ,, ..."
2,[FIRSTNAME_1] could you please share your reco...,Kattie could you please share your recomndatio...,"{'[FIRSTNAME_1]': 'Kattie', '[AGE_1]': '72', '...","[[0, 6, FIRSTNAME_1], [6, 75, O], [75, 77, AGE...","[B-FIRSTNAME, I-FIRSTNAME, O, O, O, O, O, O, O...","[kat, ##tie, could, you, please, share, your, ..."
3,Emergency supplies in [BUILDINGNUMBER_1] need ...,Emergency supplies in 16356 need a refill. Use...,"{'[BUILDINGNUMBER_1]': '16356', '[MASKEDNUMBER...","[[0, 22, O], [22, 27, BUILDINGNUMBER_1], [27, ...","[O, O, O, B-BUILDINGNUMBER, I-BUILDINGNUMBER, ...","[emergency, supplies, in, 1635, ##6, need, a, ..."
4,"The [AGE_1] old child at [BUILDINGNUMBER_1], h...","The 88 old child at 5862, has showcased an unu...","{'[AGE_1]': '88', '[BUILDINGNUMBER_1]': '5862'...","[[0, 4, O], [4, 6, AGE_1], [6, 20, O], [20, 24...","[O, B-AGE, O, O, O, B-BUILDINGNUMBER, I-BUILDI...","[the, 88, old, child, at, 58, ##6, ##2, ,, has..."
...,...,...,...,...,...,...
43496,"Hello [FIRSTNAME_1], your cognitive therapy ap...","Hello Nellie, your cognitive therapy appointme...","{'[FIRSTNAME_1]': 'Nellie', '[DATE_1]': '8/21'...","[[0, 6, O], [6, 12, FIRSTNAME_1], [12, 66, O],...","[O, B-FIRSTNAME, O, O, O, O, O, O, O, O, B-DAT...","[hello, nellie, ,, your, cognitive, therapy, a..."
43497,"Dear [FIRSTNAME_1], we appreciate your active ...","Dear Jalon, we appreciate your active involvem...","{'[FIRSTNAME_1]': 'Jalon', '[CREDITCARDNUMBER_...","[[0, 5, O], [5, 10, FIRSTNAME_1], [10, 159, O]...","[O, B-FIRSTNAME, I-FIRSTNAME, O, O, O, O, O, O...","[dear, ja, ##lon, ,, we, appreciate, your, act..."
43498,"Dear [SEX_1] at [ZIPCODE_1], we are raising fu...","Dear Female at 32363-2779, we are raising fund...","{'[SEX_1]': 'Female', '[ZIPCODE_1]': '32363-27...","[[0, 5, O], [5, 11, SEX_1], [11, 15, O], [15, ...","[O, B-SEX, O, B-ZIPCODE, I-ZIPCODE, I-ZIPCODE,...","[dear, female, at, 323, ##6, ##3, -, 277, ##9,..."
43499,"Hello [FIRSTNAME_1], we encourage you to pay t...","Hello Tito, we encourage you to pay the fees o...","{'[FIRSTNAME_1]': 'Tito', '[ETHEREUMADDRESS_1]...","[[0, 6, O], [6, 10, FIRSTNAME_1], [10, 137, O]...","[O, B-FIRSTNAME, O, O, O, O, O, O, O, O, O, O,...","[hello, tito, ,, we, encourage, you, to, pay, ..."
43500,"Due to suspect transactions, the payment throu...","Due to suspect transactions, the payment throu...","{'[MASKEDNUMBER_1]': '7677516432228268', '[CRE...","[[0, 70, O], [70, 86, MASKEDNUMBER_1], [86, 12...","[O, O, O, O, O, O, O, O, O, O, O, O, B-MASKEDN...","[due, to, suspect, transactions, ,, the, payme..."

In [6]:
def convert_privacy_mask(privacy_mask):
    """
    Converts the privacy mask dictionary in a format that is easier to process. 
    It removes brackets and splits by underscores to extract the primary entity name.

    :param privacy_mask: Dictionary where keys are entity names with additional characters.
    :return: A new dictionary with formatted entity names.
    """
    new_dict = {}
    for key, value in privacy_mask.items():
        # Remove brackets and split by underscore to get the primary entity name
        new_key = key.strip('[]').split('_')[0]
        new_dict[new_key] = value
    return new_dict

# Apply the conversion function to the 'privacy_mask' column to create 'data_results'
data['data_results'] = data['privacy_mask'].apply(convert_privacy_mask)

data[['privacy_mask', 'data_results']].head()

,privacy_mask,data_results
0,"{'[PHONEIMEI_1]': '06-184755-866851-3', '[JOBA...","{'PHONEIMEI': '06-184755-866851-3', 'JOBAREA':..."
1,"{'[FIRSTNAME_1]': 'Omer', '[VEHICLEVIN_1]': '7...","{'FIRSTNAME': 'Omer', 'VEHICLEVIN': '78B5R2MVF..."
2,"{'[FIRSTNAME_1]': 'Kattie', '[AGE_1]': '72', '...","{'FIRSTNAME': 'Kattie', 'AGE': '72', 'GENDER':..."
3,"{'[BUILDINGNUMBER_1]': '16356', '[MASKEDNUMBER...","{'BUILDINGNUMBER': '16356', 'MASKEDNUMBER': '5..."
4,"{'[AGE_1]': '88', '[BUILDINGNUMBER_1]': '5862'...","{'AGE': '88', 'BUILDINGNUMBER': '5862', 'PASSW..."

In [16]:
data_small = data

In [17]:
# An empty list to store the simplified results
model_simplified_results = []

# Through the rows of the df
for index, row in data_small.iterrows():
    text = row['unmasked_text']
    # Apply the model to the text
    result = nlp(text)

    # Simplify the model output and extract entity and word
    simplified_dict = {}
    for item in result:
        # Remove the "B-" or "I-" or "-O" prefix from the entity label
        entity = item['entity'][2:]
        word = item['word']
        # Accumulate words for each entity, separating them with space
        simplified_dict[entity] = simplified_dict.get(entity, "") + " " + word

    # Strip extra spaces from the accumulated words for each entity
    simplified_dict = {k: v.strip() for k, v in simplified_dict.items()}

    # Append the simplified dictionary to the list
    model_simplified_results.append(simplified_dict)

# Add new column with results of the model
data_small['model_results'] = model_simplified_results

In [18]:
data_small[["unmasked_text", "masked_text", "data_results", "model_results"]]

,unmasked_text,masked_text,data_results,model_results
0,A students assessment was found on device bear...,A students assessment was found on device bear...,"{'PHONEIMEI': '06-184755-866851-3', 'JOBAREA':...",{'PHONEIMEI': '06 - 1847 ##55 - 86 ##6 ##85 ##...
1,"Dear Omer, as per our records, your license 78...","Dear [FIRSTNAME_1], as per our records, your l...","{'FIRSTNAME': 'Omer', 'VEHICLEVIN': '78B5R2MVF...","{'FIRSTNAME': 'om ##er', 'SSN': '78 ##b', 'DOB..."
2,Kattie could you please share your recomndatio...,[FIRSTNAME_1] could you please share your reco...,"{'FIRSTNAME': 'Kattie', 'AGE': '72', 'GENDER':...","{'FIRSTNAME': 'kat ##tie', 'AGE': '72', 'GENDE..."
3,Emergency supplies in 16356 need a refill. Use...,Emergency supplies in [BUILDINGNUMBER_1] need ...,"{'BUILDINGNUMBER': '16356', 'MASKEDNUMBER': '5...","{'ZIPCODE': '1635 ##6', 'SSN': '58 ##90 ##7 ##..."
4,"The 88 old child at 5862, has showcased an unu...","The [AGE_1] old child at [BUILDINGNUMBER_1], h...","{'AGE': '88', 'BUILDINGNUMBER': '5862', 'PASSW...","{'AGE': '88', 'BUILDINGNUMBER': '58 ##6 ##2', ..."
...,...,...,...,...
43496,"Hello Nellie, your cognitive therapy appointme...","Hello [FIRSTNAME_1], your cognitive therapy ap...","{'FIRSTNAME': 'Nellie', 'DATE': '8/21', 'TIME'...","{'FIRSTNAME': 'nellie', 'DATE': '8 / 21', 'TIM..."
43497,"Dear Jalon, we appreciate your active involvem...","Dear [FIRSTNAME_1], we appreciate your active ...","{'FIRSTNAME': 'Jalon', 'CREDITCARDNUMBER': '38...","{'FIRSTNAME': 'ja ##lon', 'SSN': '38 ##9 ##31 ..."
43498,"Dear Female at 32363-2779, we are raising fund...","Dear [SEX_1] at [ZIPCODE_1], we are raising fu...","{'SEX': 'Female', 'ZIPCODE': '32363-2779', 'CU...","{'SEX': 'female', 'ZIPCODE': '323 ##6 ##3 - 27..."
43499,"Hello Tito, we encourage you to pay the fees o...","Hello [FIRSTNAME_1], we encourage you to pay t...","{'FIRSTNAME': 'Tito', 'ETHEREUMADDRESS': '0x2e...","{'FIRSTNAME': 'tito', 'IP': '0', 'IPV6': '##x ..."
43500,"Due to suspect transactions, the payment throu...","Due to suspect transactions, the payment throu...","{'MASKEDNUMBER': '7677516432228268', 'CREDITCA...",{'SSN': '76 ##7 ##75 ##16 ##43 ##22 ##28 ##26 ...

In [19]:
print(data_small['data_results'].apply(type).value_counts())
print(data_small['model_results'].apply(type).value_counts())

data_results
<class 'dict'>    43501
Name: count, dtype: int64
model_results
<class 'dict'>    43501
Name: count, dtype: int64

In [20]:
# Extract all unique entities from the 'data_results' column
unique_entities = set()
for _, row in data_small.iterrows():
    # Update the set with entity keys from each row's 'data_results'
    unique_entities.update(row['data_results'].keys())

# Convert the set of unique entities into a list
entity_types = list(unique_entities)

# entity_types now contains a list of all unique entities found in 'data_results' across the dataset

In [21]:
def evaluate_entry(true_entities, predicted_entities, entity_types):
    """
    Evaluates a single entry for true and predicted entities, calculating the number of true positives, false positives, and false negatives.

    :param true_entities: Dictionary of actual entities and their values.
    :param predicted_entities: Dictionary of entities predicted by the model and their values.
    :param entity_types: List of all entity types to be evaluated.
    :return: Three Counters for true positives, false positives, and false negatives.
    """
    tp, fp, fn = Counter(), Counter(), Counter()

    for entity in entity_types:
        true_value = true_entities.get(entity, '').lower()  # Fetch and lowercase the actual entity value
        predicted_value = predicted_entities.get(entity, '').lower()  # Fetch and lowercase the predicted entity value

        if true_value and true_value == predicted_value:
            tp[entity] += 1  # True positive: Entity value is correctly predicted
        elif predicted_value:
            fp[entity] += 1  # False positive: Model predicted an entity incorrectly
        if true_value and true_value != predicted_value:
            fn[entity] += 1  # False negative: Model missed an actual entity

    return tp, fp, fn

# Counters for overall true positives, false positives, and false negatives
total_tp, total_fp, total_fn = Counter(), Counter(), Counter()

# Iterate through each entry in the dataset
for index, row in data_small.iterrows():
    tp, fp, fn = evaluate_entry(row['data_results'], row['model_results'], entity_types)
    # Results for overall metrics
    total_tp += tp
    total_fp += fp
    total_fn += fn
total_tp, total_fp, total_fn

(Counter({'JOBAREA': 2207,
          'AGE': 2041,
          'GENDER': 739,
          'FIRSTNAME': 5326,
          'COUNTY': 2138,
          'JOBTITLE': 2234,
          'STREET': 1349,
          'PREFIX': 635,
          'CREDITCARDISSUER': 596,
          'MIDDLENAME': 2307,
          'LASTNAME': 1207,
          'SEX': 2364,
          'ORDINALDIRECTION': 1057,
          'TIME': 920,
          'CURRENCYSYMBOL': 1170,
          'ACCOUNTNAME': 2620,
          'STATE': 1663,
          'CURRENCY': 374,
          'EYECOLOR': 511,
          'BUILDINGNUMBER': 348,
          'PIN': 26,
          'DATE': 552,
          'JOBTYPE': 2160,
          'SECONDARYADDRESS': 433,
          'COMPANYNAME': 285,
          'HEIGHT': 259,
          'CITY': 487,
          'CREDITCARDCVV': 286,
          'CURRENCYCODE': 33,
          'DOB': 218,
          'CURRENCYNAME': 8,
          'SSN': 8,
          'PHONENUMBER': 1}),
 Counter({'PHONEIMEI': 1670,
          'FIRSTNAME': 7660,
          'DOB': 2697,
          'SSN': 8997,
          'HEIGHT': 526,
          'GENDER': 1193,
          'ZIPCODE': 1514,
          'PASSWORD': 4525,
          'BUILDINGNUMBER': 2769,
          'IPV6': 2412,
          'NEARBYGPSCOORDINATE': 1635,
          'USERAGENT': 2257,
          'EMAIL': 4088,
          'TIME': 1958,
          'EYECOLOR': 356,
          'PIN': 904,
          'LASTNAME': 3486,
          'IP': 2056,
          'MAC': 3924,
          'JOBAREA': 479,
          'IPV4': 3750,
          'CITY': 2066,
          'DATE': 4148,
          'PREFIX': 3125,
          'CREDITCARDNUMBER': 1048,
          'CREDITCARDISSUER': 892,
          'COUNTY': 800,
          'STATE': 1346,
          'CURRENCYCODE': 1454,
          'VEHICLEVRM': 1381,
          'PHONENUMBER': 5074,
          'AMOUNT': 3252,
          'MIDDLENAME': 767,
          'CURRENCY': 1840,
          'COMPANYNAME': 2315,
          'CURRENCYSYMBOL': 2182,
          'ACCOUNTNUMBER': 1290,
          'CURRENCYNAME': 465,
          'URL': 2901,
          'BITCOINADDRESS': 914,
          'SECONDARYADDRESS': 1986,
          'MASKEDNUMBER': 478,
          'USERNAME': 3134,
          'CREDITCARDCVV': 626,
          'JOBTITLE': 743,
          'STREET': 1905,
          'VEHICLEVIN': 198,
          'AGE': 311,
          'JOBTYPE': 295,
          'BIC': 550,
          'SEX': 287,
          'LITECOINADDRESS': 18,
          'ACCOUNTNAME': 157,
          'ORDINALDIRECTION': 82,
          'ETHEREUMADDRESS': 11,
          'IBAN': 1}),
 Counter({'PHONEIMEI': 1859,
          'FIRSTNAME': 7570,
          'VEHICLEVIN': 839,
          'HEIGHT': 575,
          'GENDER': 1613,
          'MASKEDNUMBER': 2110,
          'BUILDINGNUMBER': 2359,
          'PASSWORD': 2607,
          'IPV6': 2378,
          'DOB': 2117,
          'NEARBYGPSCOORDINATE': 1633,
          'USERAGENT': 2080,
          'EMAIL': 4043,
          'TIME': 1933,
          'EYECOLOR': 354,
          'PIN': 709,
          'ACCOUNTNUMBER': 2806,
          'LASTNAME': 3534,
          'JOBAREA': 651,
          'IPV4': 2701,
          'CITY': 2231,
          'DATE': 3888,
          'MIDDLENAME': 564,
          'PREFIX': 2780,
          'CREDITCARDNUMBER': 2566,
          'CREDITCARDISSUER': 911,
          'STATE': 1049,
          'VEHICLEVRM': 933,
          'JOBTYPE': 543,
          'AMOUNT': 3091,
          'CURRENCYCODE': 790,
          'BITCOINADDRESS': 2399,
          'LITECOINADDRESS': 848,
          'PHONENUMBER': 2416,
          'MAC': 1088,
          'IBAN': 1968,
          'CURRENCYNAME': 805,
          'COMPANYNAME': 2166,
          'CURRENCYSYMBOL': 1499,
          'ZIPCODE': 2290,
          'SSN': 2024,
          'CURRENCY': 1518,
          'IP': 1963,
          'URL': 2898,
          'SECONDARYADDRESS': 1870,
          'USERNAME': 2984,
          'ETHEREUMADDRESS': 1620,
          'CREDITCARDCVV': 583,
          'COUNTY': 588,
          'JOBTITLE': 705,
          'STREET': 1438,
          'AGE': 286,
          'SEX': 196,
          'BIC': 793,
          'ACCOUNTNAME': 131,
          'ORDINALDIRECTION': 47}))

In [22]:
# Store metrics for each entity
entity_metrics = {}
for entity in entity_types:
    precision = total_tp[entity] / (total_tp[entity] + total_fp[entity]) if total_tp[entity] + total_fp[entity] > 0 else 0
    recall = total_tp[entity] / (total_tp[entity] + total_fn[entity]) if total_tp[entity] + total_fn[entity] > 0 else 0
    f1 = 2 * precision * recall / (precision + recall) if precision + recall > 0 else 0
    entity_metrics[entity] = {'precision': precision, 'recall': recall, 'f1_score': f1}

entity_metrics

{'SEX': {'precision': 0.8917389664277631,
  'recall': 0.9234375,
  'f1_score': 0.9073114565342544},
 'IP': {'precision': 0.0, 'recall': 0.0, 'f1_score': 0},
 'CITY': {'precision': 0.190755973364669,
  'recall': 0.17917586460632817,
  'f1_score': 0.18478467084044775},
 'EMAIL': {'precision': 0.0, 'recall': 0.0, 'f1_score': 0},
 'CREDITCARDNUMBER': {'precision': 0.0, 'recall': 0.0, 'f1_score': 0},
 'AMOUNT': {'precision': 0.0, 'recall': 0.0, 'f1_score': 0},
 'ACCOUNTNAME': {'precision': 0.943464169967591,
  'recall': 0.9523809523809523,
  'f1_score': 0.9479015918958033},
 'ZIPCODE': {'precision': 0.0, 'recall': 0.0, 'f1_score': 0},
 'DATE': {'precision': 0.1174468085106383,
  'recall': 0.12432432432432433,
  'f1_score': 0.12078774617067835},
 'STATE': {'precision': 0.5526753074111,
  'recall': 0.6132005899705014,
  'f1_score': 0.5813668938996679},
 'CURRENCYCODE': {'precision': 0.02219233355749832,
  'recall': 0.040097205346294046,
  'f1_score': 0.02857142857142857},
 'FIRSTNAME': {'precision': 0.4101339904512552,
  'recall': 0.41299627791563276,
  'f1_score': 0.4115601576385133},
 'CURRENCYSYMBOL': {'precision': 0.3490453460620525,
  'recall': 0.4383664293742975,
  'f1_score': 0.38863976083707025},
 'NEARBYGPSCOORDINATE': {'precision': 0.0, 'recall': 0.0, 'f1_score': 0},
 'TIME': {'precision': 0.31966643502432246,
  'recall': 0.32246757798808273,
  'f1_score': 0.3210608968766359},
 'BIC': {'precision': 0.0, 'recall': 0.0, 'f1_score': 0},
 'MAC': {'precision': 0.0, 'recall': 0.0, 'f1_score': 0},
 'URL': {'precision': 0.0, 'recall': 0.0, 'f1_score': 0},
 'USERAGENT': {'precision': 0.0, 'recall': 0.0, 'f1_score': 0},
 'IPV6': {'precision': 0.0, 'recall': 0.0, 'f1_score': 0},
 'BITCOINADDRESS': {'precision': 0.0, 'recall': 0.0, 'f1_score': 0},
 'MASKEDNUMBER': {'precision': 0.0, 'recall': 0.0, 'f1_score': 0},
 'JOBAREA': {'precision': 0.8216679076693969,
  'recall': 0.77221833449965,
  'f1_score': 0.7961760461760462},
 'LITECOINADDRESS': {'precision': 0.0, 'recall': 0.0, 'f1_score': 0},
 'PASSWORD': {'precision': 0.0, 'recall': 0.0, 'f1_score': 0},
 'ETHEREUMADDRESS': {'precision': 0.0, 'recall': 0.0, 'f1_score': 0},
 'COUNTY': {'precision': 0.7277059223961879,
  'recall': 0.7842993396918562,
  'f1_score': 0.7549435028248589},
 'HEIGHT': {'precision': 0.32993630573248406,
  'recall': 0.3105515587529976,
  'f1_score': 0.31995058678196414},
 'EYECOLOR': {'precision': 0.5893886966551326,
  'recall': 0.5907514450867052,
  'f1_score': 0.5900692840646651},
 'DOB': {'precision': 0.07478559176672384,
  'recall': 0.09336188436830835,
  'f1_score': 0.08304761904761905},
 'AGE': {'precision': 0.8677721088435374,
  'recall': 0.8770949720670391,
  'f1_score': 0.8724086343235733},
 'MIDDLENAME': {'precision': 0.7504879635653872,
  'recall': 0.8035527690700105,
  'f1_score': 0.7761143818334735},
 'ORDINALDIRECTION': {'precision': 0.9280070237050044,
  'recall': 0.957427536231884,
  'f1_score': 0.9424877396344182},
 'SECONDARYADDRESS': {'precision': 0.17899958660603554,
  'recall': 0.18801563178462874,
  'f1_score': 0.18339686573485808},
 'IBAN': {'precision': 0.0, 'recall': 0.0, 'f1_score': 0},
 'CURRENCY': {'precision': 0.16892502258355918,
  'recall': 0.19767441860465115,
  'f1_score': 0.1821724305893814},
 'PIN': {'precision': 0.02795698924731183,
  'recall': 0.03537414965986395,
  'f1_score': 0.031231231231231237},
 'USERNAME': {'precision': 0.0, 'recall': 0.0, 'f1_score': 0},
 'JOBTYPE': {'precision': 0.879837067209776,
  'recall': 0.7991120976692564,
  'f1_score': 0.8375339278790228},
 'ACCOUNTNUMBER': {'precision': 0.0, 'recall': 0.0, 'f1_score': 0},
 'GENDER': {'precision': 0.38250517598343686,
  'recall': 0.31420068027210885,
  'f1_score': 0.3450046685340803},
 'JOBTITLE': {'precision': 0.7504198857910648,
  'recall': 0.7601224906430759,
  'f1_score': 0.7552400270453009},
 'VEHICLEVRM': {'precision': 0.0, 'recall': 0.0, 'f1_score': 0},
 'STREET': {'precision': 0.41456668715427164,
  'recall': 0.4840330104054539,
  'f1_score': 0.4466147988743585},
 'IPV4': {'precision': 0.0, 'recall': 0.0, 'f1_score': 0},
 'PREFIX': {'precision': 0.16888297872340424,
  'recall': 0.18594436310395315,
  'f1_score': 0.17700348432055746},
 'CURRENCYNAME': {'precision': 0.016913319238900635,
  'recall': 0.00984009840098401,
  'f1_score': 0.012441679626749611},
 'COMPANYNAME': {'precision': 0.10961538461538461,
  'recall': 0.11627906976744186,
  'f1_score': 0.11284894080380124},
 'BUILDINGNUMBER': {'precision': 0.11164581328200192,
  'recall': 0.12855559660140375,
  'f1_score': 0.1195054945054945},
 'PHONENUMBER': {'precision': 0.00019704433497536947,
  'recall': 0.0004137360364087712,
  'f1_score': 0.00026695141484249865},
 'VEHICLEVIN': {'precision': 0.0, 'recall': 0.0, 'f1_score': 0},
 'CREDITCARDISSUER': {'precision': 0.40053763440860213,
  'recall': 0.39548772395487725,
  'f1_score': 0.3979966611018364},
 'PHONEIMEI': {'precision': 0.0, 'recall': 0.0, 'f1_score': 0},
 'SSN': {'precision': 0.0008883953359244864,
  'recall': 0.003937007874015748,
  'f1_score': 0.0014496692941922623},
 'CREDITCARDCVV': {'precision': 0.31359649122807015,
  'recall': 0.3291139240506329,
  'f1_score': 0.3211678832116788},
 'LASTNAME': {'precision': 0.2571915619007032,
  'recall': 0.2545876397384518,
  'f1_score': 0.25588297646809416}}

In [23]:
# Overall metrics
overall_precision = sum(total_tp.values()) / (sum(total_tp.values()) + sum(total_fp.values())) if sum(total_tp.values()) + sum(total_fp.values()) > 0 else 0
overall_recall = sum(total_tp.values()) / (sum(total_tp.values()) + sum(total_fn.values())) if sum(total_tp.values()) + sum(total_fn.values()) > 0 else 0
overall_f1 = 2 * overall_precision * overall_recall / (overall_precision + overall_recall) if overall_precision + overall_recall > 0 else 0

# Metrics for each entity
for entity, metrics in entity_metrics.items():
    print(f"Entity: {entity}, Precision: {metrics['precision']:.2f}, Recall: {metrics['recall']:.2f}, F1-Score: {metrics['f1_score']:.2f}")

# Overall metrics
print(f"Overall Precision: {overall_precision:.2f}, Overall Recall: {overall_recall:.2f}, Overall F1-Score: {overall_f1:.2f}")

Entity: SEX, Precision: 0.89, Recall: 0.92, F1-Score: 0.91
Entity: IP, Precision: 0.00, Recall: 0.00, F1-Score: 0.00
Entity: CITY, Precision: 0.19, Recall: 0.18, F1-Score: 0.18
Entity: EMAIL, Precision: 0.00, Recall: 0.00, F1-Score: 0.00
Entity: CREDITCARDNUMBER, Precision: 0.00, Recall: 0.00, F1-Score: 0.00
Entity: AMOUNT, Precision: 0.00, Recall: 0.00, F1-Score: 0.00
Entity: ACCOUNTNAME, Precision: 0.94, Recall: 0.95, F1-Score: 0.95
Entity: ZIPCODE, Precision: 0.00, Recall: 0.00, F1-Score: 0.00
Entity: DATE, Precision: 0.12, Recall: 0.12, F1-Score: 0.12
Entity: STATE, Precision: 0.55, Recall: 0.61, F1-Score: 0.58
Entity: CURRENCYCODE, Precision: 0.02, Recall: 0.04, F1-Score: 0.03
Entity: FIRSTNAME, Precision: 0.41, Recall: 0.41, F1-Score: 0.41
Entity: CURRENCYSYMBOL, Precision: 0.35, Recall: 0.44, F1-Score: 0.39
Entity: NEARBYGPSCOORDINATE, Precision: 0.00, Recall: 0.00, F1-Score: 0.00
Entity: TIME, Precision: 0.32, Recall: 0.32, F1-Score: 0.32
Entity: BIC, Precision: 0.00, Recall: 0.00, F1-Score: 0.00
Entity: MAC, Precision: 0.00, Recall: 0.00, F1-Score: 0.00
Entity: URL, Precision: 0.00, Recall: 0.00, F1-Score: 0.00
Entity: USERAGENT, Precision: 0.00, Recall: 0.00, F1-Score: 0.00
Entity: IPV6, Precision: 0.00, Recall: 0.00, F1-Score: 0.00
Entity: BITCOINADDRESS, Precision: 0.00, Recall: 0.00, F1-Score: 0.00
Entity: MASKEDNUMBER, Precision: 0.00, Recall: 0.00, F1-Score: 0.00
Entity: JOBAREA, Precision: 0.82, Recall: 0.77, F1-Score: 0.80
Entity: LITECOINADDRESS, Precision: 0.00, Recall: 0.00, F1-Score: 0.00
Entity: PASSWORD, Precision: 0.00, Recall: 0.00, F1-Score: 0.00
Entity: ETHEREUMADDRESS, Precision: 0.00, Recall: 0.00, F1-Score: 0.00
Entity: COUNTY, Precision: 0.73, Recall: 0.78, F1-Score: 0.75
Entity: HEIGHT, Precision: 0.33, Recall: 0.31, F1-Score: 0.32
Entity: EYECOLOR, Precision: 0.59, Recall: 0.59, F1-Score: 0.59
Entity: DOB, Precision: 0.07, Recall: 0.09, F1-Score: 0.08
Entity: AGE, Precision: 0.87, Recall: 0.88, F1-Score: 0.87
Entity: MIDDLENAME, Precision: 0.75, Recall: 0.80, F1-Score: 0.78
Entity: ORDINALDIRECTION, Precision: 0.93, Recall: 0.96, F1-Score: 0.94
Entity: SECONDARYADDRESS, Precision: 0.18, Recall: 0.19, F1-Score: 0.18
Entity: IBAN, Precision: 0.00, Recall: 0.00, F1-Score: 0.00
Entity: CURRENCY, Precision: 0.17, Recall: 0.20, F1-Score: 0.18
Entity: PIN, Precision: 0.03, Recall: 0.04, F1-Score: 0.03
Entity: USERNAME, Precision: 0.00, Recall: 0.00, F1-Score: 0.00
Entity: JOBTYPE, Precision: 0.88, Recall: 0.80, F1-Score: 0.84
Entity: ACCOUNTNUMBER, Precision: 0.00, Recall: 0.00, F1-Score: 0.00
Entity: GENDER, Precision: 0.38, Recall: 0.31, F1-Score: 0.35
Entity: JOBTITLE, Precision: 0.75, Recall: 0.76, F1-Score: 0.76
Entity: VEHICLEVRM, Precision: 0.00, Recall: 0.00, F1-Score: 0.00
Entity: STREET, Precision: 0.41, Recall: 0.48, F1-Score: 0.45
Entity: IPV4, Precision: 0.00, Recall: 0.00, F1-Score: 0.00
Entity: PREFIX, Precision: 0.17, Recall: 0.19, F1-Score: 0.18
Entity: CURRENCYNAME, Precision: 0.02, Recall: 0.01, F1-Score: 0.01
Entity: COMPANYNAME, Precision: 0.11, Recall: 0.12, F1-Score: 0.11
Entity: BUILDINGNUMBER, Precision: 0.11, Recall: 0.13, F1-Score: 0.12
Entity: PHONENUMBER, Precision: 0.00, Recall: 0.00, F1-Score: 0.00
Entity: VEHICLEVIN, Precision: 0.00, Recall: 0.00, F1-Score: 0.00
Entity: CREDITCARDISSUER, Precision: 0.40, Recall: 0.40, F1-Score: 0.40
Entity: PHONEIMEI, Precision: 0.00, Recall: 0.00, F1-Score: 0.00
Entity: SSN, Precision: 0.00, Recall: 0.00, F1-Score: 0.00
Entity: CREDITCARDCVV, Precision: 0.31, Recall: 0.33, F1-Score: 0.32
Entity: LASTNAME, Precision: 0.26, Recall: 0.25, F1-Score: 0.26
Overall Precision: 0.25, Overall Recall: 0.27, Overall F1-Score: 0.26

In [15]:
# other way to calculate the metrics but doesnt work. -> must be tested
'''
#calculate metrics for each entity
metrics = {}
    # FYI: For each entity type, binary lists are created. entity_true indicates the actual presence (1)
         # or absence (0) of that entity in each record of the DataFrame. entity_pred does the same for the model's predictions.
for entity in entity_types:
    entity_true = [1 if y == entity.lower() else 0 for y in y_true]
    entity_pred = [1 if y == entity.lower() else 0 for y in y_pred]

    # -> y_true and y_pred contain actual and predicted entities for each dataset record.
        # For each entity in entity_types, we check if its corresponding value in y_true or y_pred matches the entity#s name (y == entity.lower()),
        # ensuring case-insensitive comparison.
        # If there's a match, a 1 is added to the list, indicating the presence of that entity; otherwise, a 0 is added, indicating absence.
    precision = precision_score(entity_true, entity_pred, zero_division=0)
    recall = recall_score(entity_true, entity_pred, zero_division=0)
    f1 = f1_score(entity_true, entity_pred, zero_division=0)

    metrics[entity] = {'precision': precision, 'recall': recall, 'f1_score': f1}

# calculate overall metrics
overall_precision = precision_score(y_true, y_pred, average='micro', zero_division=0)
overall_recall = recall_score(y_true, y_pred, average='micro', zero_division=0)
overall_f1 = f1_score(y_true, y_pred, average='micro', zero_division=0)

# overall metrics add to the metrics dictionary
metrics['overall'] = {'precision': overall_precision, 'recall': overall_recall, 'f1_score': overall_f1}

# metrics in a formatted way
for entity, entity_metrics in metrics.items():
    print(f"Entity: {entity}")
    print(f" Precision: {entity_metrics['precision']:.2f}")
    print(f" Recall: {entity_metrics['recall']:.2f}")
    print(f" F1-Score: {entity_metrics['f1_score']:.2f}\n")
'''

'\n#calculate metrics for each entity\nmetrics = {}\n    # FYI: For each entity type, binary lists are created. entity_true indicates the actual presence (1)\n         # or absence (0) of that entity in each record of the DataFrame. entity_pred does the same for the model\'s predictions.\nfor entity in entity_types:\n    entity_true = [1 if y == entity.lower() else 0 for y in y_true]\n    entity_pred = [1 if y == entity.lower() else 0 for y in y_pred]\n\n    # -> y_true and y_pred contain actual and predicted entities for each dataset record.\n        # For each entity in entity_types, we check if its corresponding value in y_true or y_pred matches the entity#s name (y == entity.lower()),\n        # ensuring case-insensitive comparison.\n        # If there\'s a match, a 1 is added to the list, indicating the presence of that entity; otherwise, a 0 is added, indicating absence.\n    precision = precision_score(entity_true, entity_pred, zero_division=0)\n    recall = recall_score(entity_true, entity_pred, zero_division=0)\n    f1 = f1_score(entity_true, entity_pred, zero_division=0)\n\n    metrics[entity] = {\'precision\': precision, \'recall\': recall, \'f1_score\': f1}\n\n# calculate overall metrics\noverall_precision = precision_score(y_true, y_pred, average=\'micro\', zero_division=0)\noverall_recall = recall_score(y_true, y_pred, average=\'micro\', zero_division=0)\noverall_f1 = f1_score(y_true, y_pred, average=\'micro\', zero_division=0)\n\n# overall metrics add to the metrics dictionary\nmetrics[\'overall\'] = {\'precision\': overall_precision, \'recall\': overall_recall, \'f1_score\': overall_f1}\n\n# metrics in a formatted way\nfor entity, entity_metrics in metrics.items():\n    print(f"Entity: {entity}")\n    print(f" Precision: {entity_metrics[\'precision\']:.2f}")\n    print(f" Recall: {entity_metrics[\'recall\']:.2f}")\n    print(f" F1-Score: {entity_metrics[\'f1_score\']:.2f}\n")\n'